// app/components/LocationInfoPanel.vue
<template>
    <GridLayout width="200" v-show="mShowLocationInfo"  height="70" borderRadius="40" backgroundColor="#77000000" padding="6" columns="auto,*,auto" @swipe="showLocationInfo = false">
                <CanvasLabel width="60" height="60" borderRadius="30" borderWidth="4" :borderColor="accentColor" backgroundColor="#aaffffff" >
                    <CGroup verticalAlignment="middle" textAlignment="center">
                    <CSpan :text="((currentLocation && currentLocation.speed !== undefined) ? currentLocation.speed.toFixed() : '-') + '\n'" fontSize="26" fontWeight="bold"  />
                    <CSpan text="km/h" fontSize="10" />
                    </CGroup>
                </CanvasLabel>
                <CanvasLabel col="1" marginLeft="5" color="#fff">
                    <CSpan :text="$tu('altitude') + (listeningForBarometer ? `(${$t('barometer')})`:'') + '\n'" fontSize="11" :color="accentColor" verticalAlignment="top"/>
                    <CGroup  verticalAlignment="middle">
                    <CSpan :text="currentAltitude" fontSize="20" fontWeight="bold" />
                    <CSpan text=" m" fontSize="12" />
                    </CGroup>
                </CanvasLabel>
                <label col="1" v-show="listeningForBarometer && airportRefName" :text="airportRefName" verticalAlignment="bottom" horizontalAlignment="right" color="#fff" fontSize="9" />
                <StackLayout v-show="hasBarometer" col="2" verticalAlignment="center">
                    <MDButton variant="text" class="small-icon-btn" text="mdi-gauge" @tap="switchBarometer" color="white" />
                    <MDButton variant="text" class="small-icon-btn" v-show="listeningForBarometer" text="mdi-reflect-vertical" @tap="getNearestAirportPressure" color="white" />
                </StackLayout>
            </GridLayout>
</template>
<script lang="ts" src="./LocationInfoPanel.ts"/>

// app/components/LocationInfoPanel.svelte
<script lang="ts" context="module">
    import { GridLayout } from '@akylas/nativescript';
    import { l, lu } from '@nativescript-community/l';
    import {
        getAirportPressureAtLocation,
        isSensorAvailable,
        startListeningForSensor,
        stopListeningForSensor
    } from '@nativescript-community/sensors';
    import { getAltitude } from '@nativescript-community/sensors/sensors.common';
    import { MapPos } from '@nativescript-community/ui-carto/core';
    import {
        ApplicationEventData,
        off as applicationOff,
        on as applicationOn,
        resumeEvent,
        suspendEvent
    } from '@nativescript/core/application';
    import { getNumber, getString, setNumber, setString } from '@nativescript/core/application-settings';
    import { Accuracy } from '@nativescript/core/ui/enums';
    import { onDestroy, onMount } from 'svelte';
    import { NativeViewElementNode } from 'svelte-native/dom';
    import { GeoHandler } from '~/handlers/GeoHandler';
    import { onServiceLoaded } from '~/services/BgService.common';
    import { packageService } from '~/services/PackageService';
    import { accentColor } from '~/variables';
    import { getMapContext } from '~/mapModules/MapModule';
</script>

<script lang="ts">

    let geoHandler: GeoHandler;
    let showLocationInfo = false;
    const mapContext = getMapContext();

    export function switchLocationInfo() {
        showLocationInfo = !showLocationInfo;
    }

    let hasBarometer = isSensorAvailable('barometer');
    let listeningForBarometer = false;
    let airportPressure = getNumber('airport_pressure', null);
    let airportRefName: string = getString('airport_ref', null);
    let currentAltitude: number = null;
    let shownAltitude: number | string = null;
    let currentLocation: MapPos<LatLonKeys> = null;
    let gridLayout: NativeViewElementNode<GridLayout>;

    export function getNativeView() {
        return gridLayout && gridLayout.nativeView;
    }

    $: {
        const module = mapContext.mapModule('userLocation');
        if (module) {
            if (showLocationInfo) {
                module.on('location', onNewLocation, this);
                onNewLocation({ data: module.lastUserLocation });
            } else {
                module.off('location', onNewLocation, this);
                if (listeningForBarometer) {
                    stopBarometerAltitudeUpdate();
                }
            }
        }
    }
    $: {
        if (listeningForBarometer) {
            if (!airportPressure) {
                shownAltitude = l('no_ref');
            }
            shownAltitude = currentAltitude !== null ? currentAltitude : '-';
        } else if (currentAltitude !== null) {
            shownAltitude = currentAltitude;
        } else {
            shownAltitude = currentLocation && currentLocation.altitude !== undefined ? currentLocation.altitude : '-';
        }
    }

    onMount(() => {
        applicationOn(suspendEvent, onAppPause, this);
        applicationOn(resumeEvent, onAppResume, this);
    });
    onDestroy(() => {
        applicationOff(suspendEvent, onAppPause, this);
        applicationOff(resumeEvent, onAppResume, this);
    });

    onServiceLoaded((handler: GeoHandler) => {
        geoHandler = handler;
    });

    async function onNewLocation(e: any) {
        currentLocation = e.data;
        const altitude = await packageService.getElevation(currentLocation);
        console.log('onNewLocation', currentLocation, altitude, typeof altitude);
        if (altitude !== null) {
            currentAltitude = altitude;
        }
        // console.log('onNewLocation', currentLocation);
    }
    function startBarometer() {
        if (listeningForBarometer) {
            startListeningForSensor('barometer', onSensor, 1000);
        }
    }
    function stopBarometer() {
        if (listeningForBarometer) {
            stopListeningForSensor('barometer', onSensor);
        }
    }
    function startBarometerAltitudeUpdate() {
        console.log('startBarometerAltitudeUpdate');
        if (!listeningForBarometer) {
            listeningForBarometer = true;
            startBarometer();
        }
    }
    function stopBarometerAltitudeUpdate() {
        if (listeningForBarometer) {
            stopBarometer();
            listeningForBarometer = false;
        }
    }
    function switchBarometer() {
        if (listeningForBarometer) {
            stopBarometerAltitudeUpdate();
        } else {
            startBarometerAltitudeUpdate();
        }
    }
    function getNearestAirportPressure() {
        return geoHandler.enableLocation().then(() => {
            geoHandler
                .getLocation({ desiredAccuracy: Accuracy.high, maximumAge: 120000 })
                .then((r) => getAirportPressureAtLocation(gVars.AVWX_API_KEY, r.lat, r.lon))
                .then((r) => {
                    airportPressure = r.pressure;
                    airportRefName = r.name;
                    setNumber('airport_pressure', airportPressure);
                    setString('airport_ref', airportRefName);
                    alert(`found nearest airport pressure ${r.name} with pressure:${r.pressure} hPa`);
                })
                .catch((err) => {
                    alert(`could not find nearest airport pressure: ${err}`);
                });
        });
    }
    function onSensor(data, sensor: string) {
        if (sensor === 'barometer' && airportPressure != null) {
            // we can compute altitude
            if (airportPressure) {
                // console.log('barometer', data.timestamp, data.pressure, airportPressure);
                currentAltitude = Math.round(getAltitude(data.pressure, airportPressure));
                stopBarometer();
                if (listeningForBarometer) {
                    setTimeout(() => {
                        startBarometer();
                    }, 5000);
                }
            }
        }
    }
    let wasListeningForBarometerBeforePause = false;
    let dontListenForBarometerWhilePaused = true;
    function onAppResume(args: ApplicationEventData) {
        if (wasListeningForBarometerBeforePause) {
            startBarometerAltitudeUpdate();
            wasListeningForBarometerBeforePause = false;
        }
    }
    function onAppPause(args: ApplicationEventData) {
        if (listeningForBarometer) {
            if (dontListenForBarometerWhilePaused) {
                wasListeningForBarometerBeforePause = true;
                stopBarometerAltitudeUpdate();
            }
        }
    }
</script>

<gridlayout
    {...$$restProps}
    bind:this={gridLayout}
    width="200"
    visibility={showLocationInfo ? 'visible' : 'collapsed'}
    height="70"
    borderRadius="40"
    backgroundColor="#77000000"
    padding="6"
    columns="auto,*,auto"
    on:swipe={() => (showLocationInfo = false)}>
    <canvaslabel width="60" height="60" borderRadius="30" borderWidth="4" borderColor={accentColor} backgroundColor="#aaffffff">
        <cgroup verticalAlignment="middle" textAlignment="center">
            <cspan
                text="
                        {(currentLocation && currentLocation.speed !== undefined ? currentLocation.speed.toFixed() : '-') + '\n'} "
                fontSize="26"
                fontWeight="bold" />
            <cspan text="km/h" fontSize="10" />
        </cgroup>
    </canvaslabel>
    <canvaslabel col="1" marginLeft="5" color="#fff">
        <cspan
            text={lu('altitude') + (listeningForBarometer ? `(${l('barometer')})` : '') + '\n'}
            fontSize="11"
            color={accentColor}
            verticalAlignment="top" />
        <cgroup verticalAlignment="middle">
            <cspan text={shownAltitude} fontSize="20" fontWeight="bold" />
            <cspan text=" m" fontSize="12" />
        </cgroup>
    </canvaslabel>
    <label
        col="1"
        visibility={listeningForBarometer && airportRefName ? 'visible' : 'collapsed'}
        text={airportRefName}
        verticalAlignment="bottom"
        horizontalAlignment="right"
        color="#fff"
        fontSize="9" />
    <stacklayout visibility={hasBarometer ? 'visible' : 'collapsed'} col="2" verticalAlignment="center">
        <mdbutton variant="text" class="small-icon-btn" text="mdi-gauge" on:tap={switchBarometer} color="white" />
        <mdbutton
            variant="text"
            class="small-icon-btn"
            visibility={listeningForBarometer ? 'visible' : 'collapsed'}
            text="mdi-reflect-vertical"
            on:tap={getNearestAirportPressure}
            color="white" />
    </stacklayout>
</gridlayout>
