// app/components/OptionPicker.vue
<template>
    <CollectionView for="item in options" rowHeight="50" height="200">
        <v-template>
            <GridLayout columns="*, auto" class="list-group-item" orientation="horizontal" padding="10">
                <Label fontSize="18" :text="item.name | L" col="0" verticalAlignment="center" />
                <Switch col="1" ios:backgroundColor="#f27743" v-model="item.checked" verticalAlignment="center" />
            </GridLayout>
        </v-template>
    </CollectionView>
</template>
<script lang="ts" src="./OptionPicker.ts"></script>

// app/components/OptionPicker.svelte
<script lang="ts">
    import { Template } from 'svelte-native/components';

    export let options: { name: string; checked: boolean }[];
</script>

<collectionview items={options} rowHeight="50" height="200">
    <Template let:item>
        <gridlayout columns="*, auto" class="list-group-item" orientation="horizontal" padding="10">
            <label fontSize="18" text={item.name} col="0" verticalAlignment="center" />
            <switch
                col="1"
                ios:backgroundColor="#f27743"
                checked={item.checked}
                on:onCheckedChange={(event) => (item.checked = event.value)}
                verticalAlignment="center" />
        </gridlayout>
    </Template>
</collectionview>
