// app/components/CActionBar.vue
<template>
    <GridLayout class="actionBar" columns="auto,*, auto" rows="auto,auto">
        <StackLayout col="1" colSpan="3" verticalAlignment="center" :height="height">
            <Label class="actionBarTitle" v-if="title" textAlignment="left" :text="title | capitalize" />
            <Label
                :visibility="!!subtitle ? 'visible' : 'collapse'"
                textAlignment="left"
                class="actionBarSubtitle"
                :text="subtitle"
            />
        </StackLayout>
        <ContentView col="1" colSpan="2" :height="height">
            <slot name="title"> </slot>
        </ContentView>

        <StackLayout orientation="horizontal" col="2" verticalAlignment="top" :height="height">
            <slot name="rightButtons" />
        </StackLayout>
        <ContentView col="0" verticalAlignment="top" :height="height">
            <MDButton
                rippleColor="white"
                variant="text"
                v-show="menuIconVisible"
                class="icon-btn"
                :text="menuIcon"
                @tap="onMenuIcon"
            />
        </ContentView>
        <!-- <StackLayout col="2" orientation="horizontal"> -->
        <!-- </StackLayout> -->
        <!-- <ContentView > -->
        <slot row="1" colSpan="3" name="subView" />
        <!-- </ContentView> -->
    </GridLayout>
</template>

<script lang="ts" src="./CActionBar.ts" />

// app/components/common/CActionBar.svelte
<script lang="ts">
    import { Frame } from '@nativescript/core/ui/frame';
    import { onMount } from 'svelte';
    import { closeModal, goBack } from 'svelte-native';
    import { actionBarHeight, colors, statusBarHeight } from '~/variables';
    import IconButton from './IconButton.svelte';
    import { showError } from '~/utils/error';
    $: ({ colorOnSurface } = $colors);

    export let title: string = null;
    export let showMenuIcon: boolean = false;
    export let height = $actionBarHeight;
    export let paddingTop = __ANDROID__ ? $statusBarHeight : 0;
    export let canGoBack: boolean = false;
    export let forceCanGoBack: boolean = false;
    export let modalWindow: boolean = false;
    export let disableBackButton: boolean = false;
    export let onClose: Function = null;
    export let onGoBack: Function = null;
    let menuIcon: string;
    let menuIconVisible: boolean;
    export let labelsDefaultVisualState = null;
    export let buttonsDefaultVisualState = null;

    onMount(() => {
        // setTimeout(() => {
        canGoBack = Frame.topmost() && (Frame.topmost().canGoBack() || !!Frame.topmost().currentEntry);
        // }, 0);
    });
    function onMenuIcon() {
        try {
            if (onGoBack) {
                onGoBack();
            } else if (modalWindow) {
                if (onClose) {
                    onClose();
                } else {
                    closeModal(undefined);
                }
            } else {
                goBack();
            }
        } catch (error) {
            showError(error);
        }
    }
    $: {
        if (modalWindow) {
            menuIcon = 'mdi-close';
        } else {
            menuIcon = forceCanGoBack || canGoBack ? (__IOS__ ? 'mdi-chevron-left' : 'mdi-arrow-left') : 'mdi-menu';
        }
    }
    $: menuIconVisible = ((forceCanGoBack || canGoBack || modalWindow) && !disableBackButton) || showMenuIcon;
</script>

<gridlayout class="actionBar" columns="auto,*,auto" {paddingTop} rows={`${height},auto`} {...$$restProps} on:tap={() => {}}>
    <label
        id="title"
        class="actionBarTitle"
        col={1}
        colSpan={3}
        text={title || ''}
        textAlignment="left"
        verticalTextAlignment="center"
        visibility={!!title ? 'visible' : 'hidden'}
        {...$$restProps?.titleProps}
        defaultVisualState={labelsDefaultVisualState} />
    <slot name="center" />
    <stacklayout orientation="horizontal">
        <slot name="left" />
        <mdbutton class="actionBarButton" defaultVisualState={buttonsDefaultVisualState} isVisible={menuIconVisible} text={menuIcon} variant="text" on:tap={onMenuIcon} />
    </stacklayout>
    <stacklayout col={2} orientation="horizontal">
        <slot />
    </stacklayout>
    <slot name="bottom" />
</gridlayout>
